language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install coveralls
os:
  - linux
script: coverage run --source=socman test_socman.py
after_success: coveralls
