language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

os:
  - linux

# single OSX test for now, using Python 3 from homebrew
matrix:
  include:
    - os: osx
      python: none

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv env -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source env/bin/activate; fi

install:
  - pip install coveralls

script: coverage run --source=socman test_socman.py

after_success: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls; fi
