language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

os:
  - linux

# single OSX test for now, using Python 3 from homebrew
matrix:
  include:
    - os: osx
      python:
      language: generic

install:
  - pip install tox-travis

script: tox
