language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

os:
  - linux

# single OSX test for now, using Python 3 from homebrew
matrix:
  include:
    - os: osx
      python:
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv env -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source env/bin/activate; fi

install:
  - pip install coveralls
  - pip install 'pytest>=3' pytest-cov pytest-pep8
  - pip install -e .

script: pytest --cov=socman --cov-report= --pep8 test/*

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
