environment:

  matrix:

    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python33-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install pytest"

test_script:
  - "%PYTHON%\\python.exe -m pytest -q %APPVEYOR_BUILD_FOLDER%\\test\\"
