environment:

  matrix:

    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python33-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install pytest pytest-pep8"
  - "%PYTHON%\\python.exe -m pip install -e %APPVEYOR_BUILD_FOLDER%"

test_script:
  - "%PYTHON%\\python.exe -m pytest -q --pep8 %APPVEYOR_BUILD_FOLDER%\\test\\"
